### ISSUE TITLE
452ページに対するフィードバック

### ISSUE THREAD

**Issue by furandon-pig** [LambdaNote/errata-professional-ipv6-2-1#489]
- [ ] B.2 ND Proxyの説明

```
途中でND Proxyを経由したものであるとがわかります。
　↓
途中でND Proxyを経由したものであることがわかります。
```
([「プロフェッショナルIPv6」読書会](https://read-ipv6.connpass.com/)輪読にて発見)

**Comment by k16shikano** [comment]
ありがとうございます。該当ページ用のissue #452 に転記しました（こちらは閉じます）
